npm install node-bash-title
npm install node-fetch
npm install prompt-sync
npm install colors
npm install puppeteer-extra-plugin-stealth
npm install crypto
npm install puppeteer-extra
npm install puppeteer-extra-plugin-recaptcha
npm install unique-names-generator
npm install @cliqz/adblocker-puppeteer
npm install cross-fetch
npm install axios